using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// References:
// https://github.com/SebLague/Procedural-Landmass-Generation

/// <summary>
/// Holds verticies, indices and uv coordinates for meshs generated by the mapgenerator
/// </summary>
public class MeshData
{
    /// Verticies and indices for mesh generation
    public Vector3[] vertices;
    public int[] indices;
    
    // UV coordinates
    public Vector2[] uv;

    // Running index increasing with added triangles
    int currentIndex = 0;

    public MeshData(int width, int height)
    {
        // Create buffer objects to hold data
        vertices = new Vector3[width * height];
        indices = new int[(width - 1) * (height - 1) * 6];
        uv = new Vector2[width * height];
    }

    /// <summary>
    ///  Add triangle ABC to the mesh
    /// </summary>
    public void AddTriangle(int a, int b, int c)
    {
        indices[currentIndex++] = a;
        indices[currentIndex++] = b;
        indices[currentIndex++] = c;
    }

    /// <summary>
    /// Create mesh from information given. This must not happen in multithreaded context.
    /// </summary>
    /// <returns>Mesh of MeshData</returns>
    public Mesh CreateMesh()
    {
        // Create mesh and set vertices, triangles and uv maps.
        Mesh mesh = new Mesh();
        mesh.vertices = vertices;
        mesh.triangles = indices;
        mesh.uv = uv;

        // Calculate normals for mesh for correct lighting
        mesh.RecalculateNormals();
        return mesh;
    }
}

/// <summary>
/// Class used to generate mesh based on heightmaps
/// </summary>
public class MeshGenerator
{
    /// <summary>
    /// Generate flap plane mesh (2 triangles)
    /// </summary>
    /// <param name="width">width of plane</param>
    /// <param name="height">height of plane</param>
    /// <returns>MeshData corresponding to plane</returns>
    public static MeshData GeneratePlaneMesh(float width, float height)
    {
        MeshData meshData = new MeshData(2, 2);
        float centerOffsetX = (width - 1) / 2.0f;
        float centerOffsetY = (height - 1) / 2.0f;

        for (int vertexIndex = 0, y = 0; y <= 1; y += 1)
            for (int x = 0; x <= 1; x += 1)
            {
                meshData.vertices[vertexIndex] = new Vector3(x * width - centerOffsetX, 0, centerOffsetY - y * height);
                meshData.uv[vertexIndex] = new Vector2(x, y);

                vertexIndex++;
            }

        meshData.AddTriangle(0, 1, 2);
        meshData.AddTriangle(1, 3, 2);

        return meshData;
    }

    /// <summary>
    /// Generate Mesh from Heightmap
    /// </summary>
    /// <param name="map">Heightmap</param>
    /// <param name="lod">Level of detail to be used</param>
    /// <param name="heightFactor">Multiplicator for height of mesh</param>
    /// <param name="heightFunction">Animation curve mapping input height to mesh height</param>
    /// <returns></returns>
    public static MeshData GenerateTerrainMesh(float[,] map, int lod, float heightFactor, AnimationCurve heightFunction)
    {
        if (lod < 0 || lod > 6)
            throw new ArgumentException("LOD for mesh generation must be in [0, 6]");

        // Clone heightFunction for multi-threaded access
        heightFunction = new AnimationCurve(heightFunction.keys);

        // Get width and height from map
        int width = map.GetLength(0);
        int height = map.GetLength(1);

        // Calculate offset from center
        float centerOffsetX = (width - 1) / 2.0f;
        float centerOffsetY = (height - 1) / 2.0f;

        // Transform level of detail
        lod = (lod == 0) ? 1 : lod * 2;
        int verticesPerLine = (width - 1) / lod + 1;

        // Create meshData storage object for construction
        MeshData meshData = new MeshData(verticesPerLine, verticesPerLine);

        // Iterate over map and add heights to meshData 
        for (int vertexIndex = 0, y = 0; y < height; y += lod)
            for (int x = 0; x < width; x += lod)
            {
                // Calculate vertices and UV
                meshData.vertices[vertexIndex] = new Vector3(x - centerOffsetX, heightFunction.Evaluate(map[x, y]) * heightFactor, centerOffsetY - y);
                meshData.uv[vertexIndex] = new Vector2(x / (float)width, y / (float)height);

                // Add Triangles for current position in heightmap
                if (x < width - 1 && y < height - 1)
                {
                    meshData.AddTriangle(vertexIndex, vertexIndex + verticesPerLine + 1, vertexIndex + verticesPerLine);
                    meshData.AddTriangle(vertexIndex + verticesPerLine + 1, vertexIndex, vertexIndex + 1);
                }

                // Increase index as we are going
                vertexIndex++;
            }

        // Return meshData
        return meshData;
    }
}
